# dataset cration

In [ ]:
#dataset is from https://github.com/matousp/malware-analysis/tree/main

In [1]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install requests

Requirement already satisfied: numpy in ./.venv/lib/python3.10/site-packages (2.2.6)
Requirement already satisfied: pandas in ./.venv/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in ./.venv/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.10/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.10/site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.10/site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.10/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.10/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.10/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in ./.venv/lib/python3.10/site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.10/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.10/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.10/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.10/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: requests in ./.venv/lib/python3.10/site-packages (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.10/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.10/site-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.10/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.10/site-packages (from requests) (2026.4.22)

In [2]:
import numpy as np
import json
import pandas as pd
import matplotlib.pyplot as plt
import requests
import os

In [3]:
"""
url = 'https://ja4db.com/api/read/'

response = requests.get(url)
data = response.json()
df_web = pd.DataFrame(data)
"""

"\nurl = 'https://ja4db.com/api/read/'\n\nresponse = requests.get(url)\ndata = response.json()\ndf_web = pd.DataFrame(data)\n"

In [4]:
#df_web.to_csv("ja4db.csv",index=False)

In [5]:
dataset = 'otherset/datasets'

In [6]:
daCon = pd.read_csv('otherset/desktop-apps-converted.csv')
dmCon = pd.read_csv('otherset/desktop-malware-converted.csv')
maCon = pd.read_csv('otherset/mobile-apps-converted.csv')
mmCon = pd.read_csv('otherset/mobile-malware-converted.csv')
df_web = pd.read_csv("ja4db.csv")

/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_4978/2862668647.py:5: DtypeWarning: Columns (0,1,2,3,7,8,11,13,14,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_web = pd.read_csv("ja4db.csv")

In [7]:
print(np.array(daCon.columns))
print(np.array(dmCon.columns))
print(np.array(maCon.columns))
print(np.array(mmCon.columns))
print(np.array(df_web.columns))

['SrcIP' 'DstIP' 'SrcPort' 'DstPort' 'SNI' 'OrgName' 'JA3hash' 'JA4hash'
 'AppName' 'Type' 'JA3Shash' 'JA4Shash' 'Filename' 'Version' 'JA4X1'
 'Issuer1' 'Subject1' 'JA4X2' 'Issuer2' 'Subject2' 'JA4X3' 'Issuer3'
 'Subject3']
['SrcIP' 'DstIP' 'SrcPort' 'DstPort' 'Proto' 'SNI' 'OrgName' 'TLSVersion'
 'ClientCipherSuite' 'ClientExtensions' 'ClientSupportedGroups' 'EC_fmt'
 'JA3hash' 'JA4hash' 'JA4_raw' 'AppName' 'Type' 'ServerCipherSuite'
 'ServerExtensions' 'JA3Shash' 'JA4Shash' 'JA4S_raw' 'Filename' 'Version']
['SrcIP' 'DstIP' 'SrcPort' 'DstPort' 'Proto' 'SNI' 'OrgName' 'TLSVersion'
 'ClientCipherSuite' 'ClientExtensions' 'ClientSupportedGroups' 'EC_fmt'
 'ALPN' 'SignatureAlgorithms' 'ClientSupportedVersions' 'JA3hash'
 'JA4hash' 'JA4_raw' 'AppName' 'Type' 'ServerCipherSuite'
 'ServerExtensions' 'ServerSupportedVersions' 'JA3Shash' 'JA4Shash'
 'JA4S_raw' 'Filename' 'Version']
['SrcIP' 'DstIP' 'SrcPort' 'DstPort' 'Proto' 'SNI' 'OrgName' 'TLS Version'
 'Client CipherSuite' 'Client Extensions' 'Client Supported Groups'
 'EC_fmt' 'JA3hash' 'JA4hash' 'JA4_raw' 'AppName' 'Type'
 'Server CipherSuite' 'Server Extensions' 'JA3Shash' 'JA4Shash' 'JA4S_raw'
 'Filename' 'Version']
['application' 'library' 'device' 'os' 'user_agent_string'
 'certificate_authority' 'observation_count' 'verified' 'notes'
 'ja4_fingerprint' 'ja4_fingerprint_string' 'ja4s_fingerprint'
 'ja4h_fingerprint' 'ja4x_fingerprint' 'ja4t_fingerprint'
 'ja4ts_fingerprint' 'ja4tscan_fingerprint']

In [8]:
common_strings = list(set(np.array(daCon.columns)).intersection(np.array(dmCon.columns), np.array(maCon.columns), np.array(mmCon.columns)))

In [9]:
common_strings

['SrcPort',
 'SNI',
 'AppName',
 'DstPort',
 'JA3Shash',
 'JA3hash',
 'JA4hash',
 'Type',
 'SrcIP',
 'Version',
 'Filename',
 'OrgName',
 'DstIP',
 'JA4Shash']

In [10]:
dmCon["Filename"].unique()[0]

'tests/malware2/ICEDID/240520-scyd1afd51.behavioral2-extracted.csv'

In [11]:
attack_word = "Attack"
label_word = "Label"
final_inculsion_header = common_strings

In [12]:
final_inculsion_header.append(label_word)

In [13]:
final_inculsion_header.append(attack_word)

In [14]:
final_inculsion_header

['SrcPort',
 'SNI',
 'AppName',
 'DstPort',
 'JA3Shash',
 'JA3hash',
 'JA4hash',
 'Type',
 'SrcIP',
 'Version',
 'Filename',
 'OrgName',
 'DstIP',
 'JA4Shash',
 'Label',
 'Attack']

In [15]:
print(daCon["Filename"].unique()[0].split("/"))
print(dmCon["Filename"].unique()[0].split("/"))
print(maCon["Filename"].unique()[0].split("/"))
print(mmCon["Filename"].unique()[0].split("/"))

['tests', 'ondra2', 'AMPLibraryAgent-extracted.csv']
['tests', 'malware2', 'ICEDID', '240520-scyd1afd51.behavioral2-extracted.csv']
['tests', 'apps3', 'snapchat_03-11-extracted.csv']
['tests', 'malware4', 'android11', 'smart_walk_03-extracted.csv']

In [16]:

result = [str(item).split('/') for item in dmCon["Filename"]]
result2 = [
    str(item).split('/')[2] if len(str(item).split('/')) >= 3 else "NAN" 
    for item in dmCon["Filename"].unique()
]

print(np.unique(result2))
result = [str(item) for item in mmCon["Type"]]
result = [
    "MALWARE" if item == "M" 
    else "advertising/analytics" if item == "A" 
    else "NAN"
    for item in mmCon["Type"]
]

print(np.unique(result))

['AGENTTESLA' 'ASYNCRAT' 'AZORULT' 'BAZARBACKDOOR' 'DARKCOMET' 'DRIDEX'
 'EMOTET' 'FORMBOOK' 'GOZI_IFSB' 'HAWKEYE' 'HAWKEYE_REBORN' 'ICEDID'
 'LOKIBOT' 'MASSLOGGER' 'MATIEX' 'METASPLOIT' 'MODILOADER' 'NAN'
 'NANOCORE' 'NETWIRE' 'NJRAT' 'PONY' 'QAKBOT' 'QNODESERVICE' 'RACCOON'
 'REMCOS' 'REVENGERAT' 'SMOKELOADER' 'SODINOKIBI' 'TRICKBOT' 'UPATRE'
 'WANNACRY' 'YUNSIP' 'ZLOADER']
['MALWARE' 'advertising/analytics']

In [17]:
daCon[label_word] = ["NORMAL" for item in daCon["Filename"]]
dmCon[label_word] =[
    str(item).split('/')[2] if len(str(item).split('/')) >= 3 else None 
    for item in dmCon["Filename"]
]
maCon[label_word] = ["NORMAL" for item in maCon["Filename"]]
mmCon[label_word] = [
    "MALWARE" if item == "M" 
    else "advertising/analytics" if item == "A" 
    else "NAN"
    for item in mmCon["Type"]
]

In [18]:
daCon[attack_word] = 0
dmCon[attack_word] = 1
maCon[attack_word] = 0
mmCon[attack_word] = 1

In [20]:
temdsf = [daCon[final_inculsion_header],dmCon[final_inculsion_header],maCon[final_inculsion_header],mmCon[final_inculsion_header]] 
dsf = pd.concat(temdsf)

In [28]:
df_web.head()

,application,library,device,os,user_agent_string,certificate_authority,observation_count,verified,notes,ja4_fingerprint,ja4_fingerprint_string,ja4s_fingerprint,ja4h_fingerprint,ja4x_fingerprint,ja4t_fingerprint,ja4ts_fingerprint,ja4tscan_fingerprint
0,Nmap,NaN,NaN,NaN,NaN,NaN,1.0,True,NaN,NaN,NaN,NaN,NaN,NaN,1024_2_1460_00,NaN,NaN
1,NaN,NaN,NaN,NaN,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,1.0,False,NaN,t13d1517h2_8daaf6152771_b0da82dd1658,"t13d1517h2_002f,0035,009c,009d,1301,1302,1303,...",NaN,ge11cn20enus_60ca1bd65281_ac95b44401d9_8df6a44...,NaN,NaN,NaN,NaN
2,NaN,Python,NaN,NaN,NaN,NaN,1.0,True,NaN,t13i181000_85036bcba153_d41ae481755e,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Chromium Browser,NaN,NaN,NaN,NaN,NaN,1.0,True,NaN,t13d1516h2_8daaf6152771_02713d6af862,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Chromium Browser,NaN,NaN,NaN,NaN,NaN,1.0,True,NaN,q13d0312h3_55b375c5d22e_06cda9e17597,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
dsf.columns

Index(['SrcPort', 'SNI', 'AppName', 'DstPort', 'JA3Shash', 'JA3hash',
       'JA4hash', 'Type', 'SrcIP', 'Version', 'Filename', 'OrgName', 'DstIP',
       'JA4Shash', 'Label', 'Attack'],
      dtype='object')

In [27]:
df_web.columns

Index(['application', 'library', 'device', 'os', 'user_agent_string',
       'certificate_authority', 'observation_count', 'verified', 'notes',
       'ja4_fingerprint', 'ja4_fingerprint_string', 'ja4s_fingerprint',
       'ja4h_fingerprint', 'ja4x_fingerprint', 'ja4t_fingerprint',
       'ja4ts_fingerprint', 'ja4tscan_fingerprint'],
      dtype='object')

In [34]:
df_web['ja4s_fingerprint'].unique()

array([nan, 't130200_1301_a56c5b993250', 't120300_c030_5e2616a54c73',
       't120300_c030_52d195ce1d92', 't120300_009f_cef8820c8f19'],
      dtype=object)

In [37]:
ja4_web_vailed_labels = ['application','ja4_fingerprint','ja4s_fingerprint']

In [23]:
df = dsf.sample(frac=1, random_state=42).reset_index(drop=True)

In [36]:
df.to_csv("dataset.csv",index=False)

In [35]:
label_counts = df[attack_word].value_counts()
label_percentages = df[attack_word].value_counts(normalize=True) * 100


display_distibution = pd.DataFrame(
    {"count": label_counts, "percentage": label_percentages}
)
display(display_distibution)

        count  percentage
Attack
1       24153   78.766632
0        6511   21.233368